name: Node.js CI/CD Pipeline

on:
  push:
    branches: 
            main 

  pull_request:
    branches:
            main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      - name: Build the Project
        run: npm run build
        working-directory: ./app